import Head from "next/head";
import { PrismaClient } from "@prisma/client";
import { User } from "@prisma/client";

export default function Home({ allUsers, allRecipes }: { allUsers: User[]; allRecipes: any }) {
  console.log(allUsers);
  console.log(allRecipes);
  return (
    <>
      <Head>
        <title>SQL Lite + Prisma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello world</h1>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const prisma = new PrismaClient();

  const allUsers = await prisma.user.findMany({
    include: {
      recipes: true,
    },
  });

  const allRecipes = await prisma.recipe.findMany({
    include: {
      author: true,
    },
  });

  return {
    props: {
      allUsers: JSON.parse(JSON.stringify(allUsers)),
      allRecipes: JSON.parse(JSON.stringify(allRecipes)),
    },
  };
}
